### ISSUE TITLE
Marking last post as private set the condition for entire site

### ISSUE THREAD

**Issue by Rbendor** [code-atlantic/content-control#19]
Hello,
When i set the contact protect for the last post i get the redirect for the entire website.
Any ideas?

Follow-value.com

**Comment by danieliser** [comment]
@Rbendor - sorry for the delay. Can you elaborate on how the issue you saw was caused.

Your saying you had targeted multiple pages, then marked one of those pages as private?

**Comment by juanpineiro** [comment]
@danieliser I have the same problem in a site.
If i have one rule such as "mark as private all post with tag 'acceso restringido'" and the first post in the loop match that rule then the page redirect to login.
For example we have that problem in a category page that we only have 6 posts all matching the rule before mentioned then the category page redirect to login, but if i make the first post not match the rule then the category page is visible (but the excerpt of each post matching that rule it shows a message that the content is private).

**Comment by danieliser** [comment]
@juanpineiro It kinda sounds like the opposite of the original post. Your saying the first in the loop can cause it not to redirect, this topic was about the last in the list causing all to redirect.

Not sure they are related or different, but sound like opposite ends of the spectrum.

That said I'm not sure how it would be ideal in your case. You wouldn't want them redirected if there were posts for them to view which is why it doesn't redirect now.
