### ISSUE TITLE
Button "Add a Restriction" - Does not work

### ISSUE THREAD

**Issue by stalkerxxl** [code-atlantic/content-control#31]
Hmm .. after installation to WP version 5.5 - I press the Add a Restriction and nothing happens ... tested on two sites .. what could be the problem?

**Comment by emadbagheri96** [comment]
Same here
Console shows these errors:
```
Uncaught SyntaxError: expected expression, got ','
Uncaught ReferenceError: jp_cc_restriction_fields is not defined
```
this line is not working properly :
https://github.com/JunglePlugins/Content-Control/blob/d995cda5c6dfeaa8251e63b93e7dce19e04f8093/classes/Admin/Settings/Restrictions.php#L31

**Comment by danieliser** [comment]
Are you getting any PHP errors? If not then that doesn't make much since as that code is not dependent on WordPress other than maybe using the apply_filters function.

What PHP version?

**Comment by emadbagheri96** [comment]
php version is 7.3.21
and the errors are what i said

here is the picture of it
![image](https://user-images.githubusercontent.com/21096918/101614341-13c66400-3a22-11eb-8427-56ccfec345ba.png)

seems like this line is returning nothing to the html from the php code i said earlier:
![image](https://user-images.githubusercontent.com/21096918/101614535-51c38800-3a22-11eb-856f-4eb2d24e4736.png)

and yes i tested with other wordpress versions (5.3 - 5.4 - 5.6) and it didnt help

**Comment by danieliser** [comment]
@emadbagheri96 Correct, but we already knew that from your first response. What is less obvious is why a function that returns an array would come back without even showing as an empty string.

With that not easily duplicatable it likely means that either your site has a conflict or custom filters on the conditions, or an error in PHP during the get_conditions() method:

https://github.com/JunglePlugins/Content-Control/blob/d995cda5c6dfeaa8251e63b93e7dce19e04f8093/classes/Conditions.php#L85-L92

https://github.com/JunglePlugins/Content-Control/blob/d995cda5c6dfeaa8251e63b93e7dce19e04f8093/classes/Conditions.php#L422-L454

Since all that code is self contained except the call to `apply_filters`, unless something is filtering `jp_cc_registered_conditions` this seems impossible short of some error occurring in PHP which would be logged.

**Comment by danieliser** [comment]
@emadbagheri96 You might check what your Conditions class looks like, make sure the file exists and what not. Maybe your copy is corrupted somehow?

**Comment by emadbagheri96** [comment]
Checked them all, every thing exists  and yes you were right. it has problem with this plugin:
https://wordpress.org/plugins/wp-parsidate/
when i disable it, content control works fine
