### ISSUE TITLE
not working with MEC sidebar?

### ISSUE THREAD

**Issue by mathiasdg** [code-atlantic/content-control#38]
dear,

I'm using Modern Event Calendar (MEC), and on my booking page I have the MEC sidebar, which I only want to show if people are logged in. If I customise the sidebar and choose "logged in only" from the dropdown, there is no change.
But when I make my own sidebar with own HTML, then the content-control plugin works as it should.

So... is this plugin not compatible with MEC? or is MEC blocking this function?

Is there an easy work around?

**Comment by danieliser** [comment]
I believe you left a topic on wordpress.org which I've already responded too. Ultimately we hook in to the widget editor and rendering system. Either they are not using the built in API's for managing & rendering sidebars or they have done it in a way that prevents the normal methods of hooking in to filter them.

Otherwise as we tap into the WP core stuff directly, as long as they use those components it should just work.
