### ISSUE TITLE
Filter out restricted post categories before rendering the blog home or post archive pages

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#45]
## Use Case 

Right now, when I:

1. Set up a **restriction** to show posts with category = _Test_ to only **administrator** and **tester** roles
2. Have my most recent 10 posts in the _Test_ category
3. Have several other posts not in the _Test_ category

Then when I go to my **blog index** page, I'll either get redirected to a login page or get a message saying nothing found.

It'd be great to see the **blog home** or **post archive** page with my other posts when I'm not logged in as an admin or tester. I.e., exclude the _Test_  category from the main query for all non logged-in, non-admin, and non-tester accounts.

**Comment by danieliser** [comment]
We can try to tackle this but the complexity of making it both work reliably and compatibly with all the existing plugins out there is tough.

1. Filtering posts in the loop is not viable. If you wanted 10 items per page, and 5 were restricted, you would only get 5 rendered.

2. Filtering queries is not gonna be super efficient either. Because users can configure different rulesets that affect different users differently, choosing how to filter out content will be tough.

For example. Say you only want users with role A to see posts with tag B.

Well think about that, to query for all other users we would need a list of post IDs in tag B (extra query), then to filter the query to exclude those post IDs.

In this case that example is not great as we could filter out by tag possibly, but the point remains.

To exclude stuff, you generally have to have a list of all the items to exclude. That list of items could be different for every user.

----

Doable but we have to come up with creative solutions so that we aren't adding a ton of extra queries and processing during every page load.

That could be a custom table or 2 that maps what each user should/shouldn't be able to see and regenerates it regularly. Probably not terribly efficient without some background process.

Or we could hope servers are just powerful enough to handle 3-4 extra queries on every page load without much hit.

Hard to say til we try to build it I guess.

**Comment by marklchaves** [comment]
### WooCommerce Use Case

1. Create a product attribute called "Test".
2. Create a product that has a **Test** attribute with value **test-1**.
3. Create a _redirect_ restriction for logged-in visitors who have a specific role e.g., "wholesale" so they **cannot** see a product with attribute Test = "test-1".
4. Visit the **Shop** page logged in with the **wholesale** role. If this **Shop** page contains the product you created in **Step 2**, you won't be able to see the page because of the restriction created in **Step 3**.
5. You'll be redirected to your login page even though there are products on the **Shop** page with no restrictions.

**Comment by danieliser** [comment]
I think we got pretty close on this now, we can `Hide` posts as an option for archives.
