### ISSUE TITLE
Hardly Works and Restricting Other Child ID of the Same Parent Taxonomy

### ISSUE THREAD

**Issue by soamodu** [code-atlantic/content-control#72]
<img width="1232" alt="Screenshot 2023-05-21 at 8 43 23 PM" src="https://github.com/code-atlantic/content-control/assets/69548824/f2d029d3-4e15-431a-ae92-a0e8f958601d">

In my case, in the image, it restricts both the free and source prompts (which is for the pro). It was all working fine until just yesterday and WordPress has been releasing a couple of updates even plugins. I'm thinking this is the cause and I did some updating.  This current version of the content control plugin hasn’t been tested with the last few version of WordPress. Please any help please all my work of the past few weeks rely on this plugin. I'll really appreciate any help, please.

**Comment by danieliser** [comment]
@soamodu - Apologies for not seeing this sooner. In general though nothing on our end seems to be breaking during testing on clean installs, so my first guess would be caching needs purged after all the updates, second guess would be something is interfering some way, but where & how would depend on the type of restriction.

All that said we are very close to releasing v2 which is a massive rewrite, it is going into beta this week likely. I would suggest testing it on a staging site however as there are data changes, though from the looks of it you only have one restriction so you could probably just go for it and recreate if you really needed.

In general though this is only for managing known issues, not support. We only create something here if we have already deduced the issue is something we need to correct in our code essentially, not for troubleshooting problems with usage/conflicts etc as we have dedicated support team for that.
